[package]
name = "riscvemu"
version = "0.1.0"
edition = "2021"

[dependencies]
elf = "0.7"
queues = "1.1.0"
thiserror = "1.0"
num = "0.4"
itertools = "0.12"
clap = { version = "4.4.10", features = ["derive","wrap_help"] }

[[bin]]
name = "elf2trace"

[[bin]]
name = "emulate"
